apiVersion: apps/v1
kind: Deployment
metadata:
  name: less-two
  namespace: homework
  labels:
    app: homework
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1        # при обновлении может быть недоступен максимум 1 под
  selector:
    matchLabels:
      app: homework
  template:
    metadata:
      labels:
        app: homework
    spec:
      nodeSelector:
        homework: "true"
      initContainers:
      - name: init-html-gen
        image: busybox:1.36
        command:
          - /bin/sh
          - -c
          - |
            echo "<h1>Hello from init-container</h1>" > /init/index.html
            echo "File created at: $(date)" >> /init/index.html
            ls -la /init/
        volumeMounts:
        - name: homework-volume
          mountPath: /init
      containers:
      - name: web-server
        image: python:3.14.3-alpine
        command:
          - /bin/sh
          - -c
          - |
            cd /homework
            python -m http.server 8000 # open 8000 python web
        readinessProbe:
            exec:
              command:
              - test
              - -f
              - /homework/index.html
            initialDelaySeconds: 5
            periodSeconds: 5
        ports:
          - containerPort: 8000
        volumeMounts:
          - name: homework-volume
            mountPath: /homework
        lifecycle:
          
          preStop:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  rm -f /homework/index.html
                  ls -la /homework/ || true
      volumes:
      - name: homework-volume
        emptyDir: {}